version: "3.8"

services:
  php:
    build: .
    container_name: php_apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    tty: true
